# Generated by Django 2.2.2 on 2019-06-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_investment_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
