# Generated by Django 2.2.2 on 2019-07-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20190629_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='site',
            field=models.URLField(blank=True),
        ),
    ]
